### ISSUE TITLE
setup.py install fails on Windows

### ISSUE THREAD

**Issue by cmoriarty** [stevemarple/python-zwoasi#1]
I seem to be having some configuration related problems when I try to run "setup.py install".  I am using Windows 7 and I have the latest python installed (3.6).  Is there something obvious I need to do before trying to install this?  Here is the output:

C:\asi_sdk\python-zwoasi>python setup.py install
\==================================
['zwoasi']
\==================================
running install
running bdist_egg
running egg_info
writing zwoasi.egg-info\PKG-INFO
writing dependency_links to zwoasi.egg-info\dependency_links.txt
writing requirements to zwoasi.egg-info\requires.txt
writing top-level names to zwoasi.egg-info\top_level.txt
reading manifest file 'zwoasi.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'zwoasi.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\zwoasi
copying build\lib\zwoasi\__init__.py -> build\bdist.win-amd64\egg\zwoasi
byte-compiling build\bdist.win-amd64\egg\zwoasi\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying zwoasi.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying zwoasi.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying zwoasi.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying zwoasi.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying zwoasi.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\zwoasi-0.0.10-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing zwoasi-0.0.10-py3.6.egg
Removing c:\users\<removed>\appdata\local\programs\python\python36\lib\site-packages\zwoasi-0.0.10-py3.6.egg
Copying zwoasi-0.0.10-py3.6.egg to c:\users\<removed>\appdata\local\programs\python\python36\lib\site-packages
zwoasi 0.0.10 is already the active version in easy-install.pth

Installed c:\users\<removed>\appdata\local\programs\python\python36\lib\site-packages\zwoasi-0.0.10-py3.6.egg
Processing dependencies for zwoasi==0.0.10
Searching for scipy
Reading https://pypi.python.org/simple/scipy/
Downloading https://pypi.python.org/packages/f8/85/37e205d2c48a9691078bd3cd6b22237e399dc1ba049d31ba8e57da44b5be/scipy-0.18.1.zip#md5=99127abce294eaf76
eafb80ef431bb9b
Best match: scipy 0.18.1
Processing scipy-0.18.1.zip
Writing C:\Users\<removed>\AppData\Local\Temp\easy_install-cpxesyi9\scipy-0.18.1\setup.cfg
Running scipy-0.18.1\setup.py -q bdist_egg --dist-dir C:\Users\<removed>\AppData\Local\Temp\easy_install-cpxesyi9\scipy-0.18.1\egg-dist-tmp-ffsvnm0e
C:\Users\<removed>\AppData\Local\Temp\easy_install-cpxesyi9\scipy-0.18.1\setup.py:322: UserWarning: Unrecognized setuptools command, proceeding with ge
nerating Cython sources and expanding templates
  warnings.warn("Unrecognized setuptools command, proceeding with "
C:\Users\<removed>\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projec
ts\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
  pre_dirs = system_info.get_paths(self, section, key)
C:\Users\<removed>\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
C:\Users\<removed>\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
C:\Users\<removed>\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
Running from scipy source directory.
error: no lapack/blas resources found

**Comment by cmoriarty** [comment]
I solved this by manually installing numpy+mlk and scipy using whl files found here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy

On to the next problem!  I was able to run setup.py install, and then I gave the example a try.  It fires up nicely, but then fizzles out with a timeout error at the end:

C:\asi_sdk\python-zwoasi\zwoasi\examples>python zwoasi_demo.py
Found one camera: Camera #0: b'ZWO ASI1600MM'

Camera controls:
    b'AutoExpMaxBrightness':
        ControlType: 12
        DefaultValue: 100
        Description: b'Auto exposure maximum brightness value'
        IsAutoSupported: False
        IsWritable: True
        MaxValue: 160
        MinValue: 50
        Name: b'AutoExpMaxBrightness'
    b'AutoExpMaxExp':
        ControlType: 11
        DefaultValue: 30
        Description: b'Auto exposure maximum exposure value(unit second)'
        IsAutoSupported: False
        IsWritable: True
        MaxValue: 60
        MinValue: 1
        Name: b'AutoExpMaxExp'
    b'AutoExpMaxGain':
        ControlType: 10
        DefaultValue: 300
        Description: b'Auto exposure maximum gain value'
        IsAutoSupported: False
        IsWritable: True
        MaxValue: 600
        MinValue: 0
        Name: b'AutoExpMaxGain'
    b'BandWidth':
        ControlType: 6
        DefaultValue: 50
        Description: b'USB bandwidth percentage'
        IsAutoSupported: True
        IsWritable: True
        MaxValue: 100
        MinValue: 40
        Name: b'BandWidth'
    b'Brightness':
        ControlType: 5
        DefaultValue: 10
        Description: b'Brightness'
        IsAutoSupported: False
        IsWritable: True
        MaxValue: 60
        MinValue: 0
        Name: b'Brightness'
    b'Exposure':
        ControlType: 1
        DefaultValue: 10000
        Description: b'Exposure Time(us)'
        IsAutoSupported: True
        IsWritable: True
        MaxValue: 2000000000
        MinValue: 32
        Name: b'Exposure'
    b'Flip':
        ControlType: 9
        DefaultValue: 0
        Description: b'Flip: 0->None 1->Horiz 2->Vert 3->Both'
        IsAutoSupported: False
        IsWritable: True
        MaxValue: 3
        MinValue: 0
        Name: b'Flip'
    b'Gain':
        ControlType: 0
        DefaultValue: 0
        Description: b'Gain'
        IsAutoSupported: True
        IsWritable: True
        MaxValue: 600
        MinValue: 0
        Name: b'Gain'
    b'Gamma':
        ControlType: 2
        DefaultValue: 50
        Description: b'Gamma'
        IsAutoSupported: False
        IsWritable: True
        MaxValue: 100
        MinValue: 1
        Name: b'Gamma'
    b'HardwareBin':
        ControlType: 13
        DefaultValue: 0
        Description: b'Is hardware bin2:0->No 1->Yes'
        IsAutoSupported: False
        IsWritable: True
        MaxValue: 1
        MinValue: 0
        Name: b'HardwareBin'
    b'HighSpeedMode':
        ControlType: 14
        DefaultValue: 0
        Description: b'Is high speed mode:0->No 1->Yes'
        IsAutoSupported: False
        IsWritable: True
        MaxValue: 1
        MinValue: 0
        Name: b'HighSpeedMode'
    b'Pattern adjust':
        ControlType: 20
        DefaultValue: 0
        Description: b'make brightness accordant'
        IsAutoSupported: False
        IsWritable: True
        MaxValue: 4
        MinValue: 0
        Name: b'Pattern adjust'
    b'Temperature':
        ControlType: 8
        DefaultValue: 20
        Description: b'Sensor temperature(degrees Celsius)'
        IsAutoSupported: False
        IsWritable: False
        MaxValue: 1000
        MinValue: -500
        Name: b'Temperature'
Capturing a single 8-bit mono image
Traceback (most recent call last):
  File "zwoasi_demo.py", line 61, in <module>
    camera.capture(filename=filename)
  File "C:\Users\-\AppData\Local\Programs\Python\Python36\lib\site-packages\zwoasi-0.0.10-py3.6.egg\zwoasi\__init__.py", line 457, in capture
  File "C:\Users\-\AppData\Local\Programs\Python\Python36\lib\site-packages\zwoasi-0.0.10-py3.6.egg\zwoasi\__init__.py", line 407, in get_data
_after_exposure
  File "C:\Users\-\AppData\Local\Programs\Python\Python36\lib\site-packages\zwoasi-0.0.10-py3.6.egg\zwoasi\__init__.py", line 253, in _get_dat
a_after_exposure
zwoasi.ZWO_Exception: Timeout

C:\asi_sdk\python-zwoasi\zwoasi\examples>

**Comment by stevemarple** [comment]
The recommended method to install is to use pip:
pip install zwoasi

As matlabplot, numpy and scipy are listed as requirements they should be installed automatically.

The image timeout occurs fetching the data after stills capture. Are you using a USB3 interface? I've added some code to 0.0.11 which checks the exposure status is correct. Please try this version and post any error message.

**Comment by cmoriarty** [comment]
Ok, "pip install zwoasi" works nicely.  

Yes, I am using the USB3 interface.  I updated to the latest code, and I'm still seeing an error.  Although, this time I got a dialog that said Python stopped working, and the output is different:

Capturing a single 8-bit mono image
Traceback (most recent call last):
  File "zwoasi_demo.py", line 61, in <module>
    camera.capture(filename=filename)
  File "C:\Users\moriartyp\AppData\Local\Programs\Python\Python36\lib\site-packages\zwoasi\__init__.py", line 458, in capture
    raise ZWO_Exception('Exposure problem (status was %d)' % status)
zwoasi.ZWO_Exception: Exposure problem (status was 3)

**Comment by stevemarple** [comment]
Thanks, that helps. 3 = ASI_EXP_FAILED "exposure failed, you need to start exposure again".

There are several differences here compared to my setup. Firstly you are using Windows and I've only tested under Linux so far (I'm trying Windows now - what did you do to find ASI SDK DLL?). Secondly you are using a cooled camera and I'm not sure if that requires different behaviour (eg waiting until the preset temperature is reached).

I'm investigating.

**Comment by cmoriarty** [comment]
I have the ASI1600MM, which doesn't have a fan.  I don't think it's a cooled version.  

I noticed in your code that you call:
zwolib_file = os.getenv('ZWO_ASI_LIB') or 'libASICamera2.so'
zwolib = c.cdll.LoadLibrary(zwolib_file)

So I added an environment variable called ZWO_ASI_LIB that points to the ASICamera2.dll that came with the SDK.  I have tried both x86 and x64 setups.  They both end up with the same result.  

Thanks for investigating.

**Comment by stevemarple** [comment]
That's the correct procedure to locate the DLL (Windows) or .so (Linux). Perhaps I can improve on it but it works for now.

I've uploaded 0.0.12 to PyPi for install/upgrade via pip. I'm now using PIL instead of cv2 to save images. The demo program worked correctly under Windows 10 (64 bit version) on a VirtualBox virtual machine. Perhaps some other initialisation is required for the ASI1600MM that I haven't included. The latest version of the demo program now exits video mode before capturing the first stills image, just in case that was already active.

**Comment by cmoriarty** [comment]
Still fails with "status was 3" (output below).  I'll look through the sdk examples to try and find a clue as to what I'm missing.  

I'm using a Windows 7 virtual machine on VMware Fusion.  The computer that will be controlling the camera is a Windows machine, so I'm strapped to microsoft for now.  I'm able to run other apps like Fire Capture on it, so I don't think it's a USB issue.  Either way, I will post back if I ever get it working.  Thanks for all the help. 

Enabling stills mode
Capturing a single 8-bit mono image
Traceback (most recent call last):
  File "C:/Users/moriartyp/PycharmProjects/ZwoSdk/zwoasi_demo.py", line 69, in <module>
    camera.capture(filename=filename)
  File "C:\Users\moriartyp\AppData\Local\Programs\Python\Python36\lib\site-packages\zwoasi\__init__.py", line 458, in capture
    raise ZWO_Exception('Exposure problem (status was %d)' % status)
zwoasi.ZWO_Exception: Exposure problem (status was 3)

**Comment by cmoriarty** [comment]
I have abandoned the VMWare Fusion environment, and instead am using OS X  (my laptop's native OS).   I was able to load the SDK's mac friendly .dylib, and after some configuration I was able take an exposure using your zwoasi_demo.py script!

Oddly enough, only the ASI_IMG_RAW8 type works.  It fails after setting it to ASI_IMG_RAW16 and tries to capture.  At first I thought perhaps this was a limitation of my specific camera (ASI1600MM), although nothing in the documentation confirms that.  Any thoughts?

**Comment by stevemarple** [comment]
I had to make some changes for 16 bit captures, (https://github.com/stevemarple/python-zwoasi/commit/52ce920229dec9019d22e303c236a6966ca4b7a0), did you try the latest version of the demo program? If you had to make any configuration changes to work with OS X or ASI 1600MM can you please post them and the exception traceback so I can investigate some more?

**Comment by cmoriarty** [comment]
I did get the latest, and I was still having an issue.  I heard back from ZWO and they told me to lower the usb bandwidth setting.  From your demo script, I saw that it was set at "50".  So I lowered it to "40" and it worked.  Now I'm getting an exception in single 8-bit mono frame:

Enabling stills mode
Capturing a single 8-bit mono image
Saved to image_mono.jpg
Camera settings saved to image_mono.jpg.txt
Capturing a single 16-bit mono image
Saved to image_mono16.tiff
Camera settings saved to image_mono16.tiff.txt
Color image not available with this camera
Enabling video mode
Capturing a single 8-bit mono frame
Traceback (most recent call last):
  File "/Users/moriarty/PycharmProjects/ZwoAsi/zwoasi_demo.py", line 163, in <module>
    camera.capture_video_frame(filename=filename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zwoasi/__init__.py", line 491, in capture_video_frame
    data = self.get_video_data(buffer=buffer, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zwoasi/__init__.py", line 424, in get_video_data
    return _get_video_data(self.id, timeout, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zwoasi/__init__.py", line 191, in _get_video_data
    r = zwolib.ASIGetVideoData(id, cbuf, sz, timeout)
ctypes.ArgumentError: argument 4: <class 'TypeError'>: wrong type

**Comment by cmoriarty** [comment]
It looks like __init__.py (191) is trying to pass a float into an int, for the 4th parameter. 

I changed it to:
    r = zwolib.ASIGetVideoData(id, cbuf, sz, int(timeout))

Now I'm getting this:
Enabling stills mode
Capturing a single 8-bit mono image
Saved to image_mono.jpg
Camera settings saved to image_mono.jpg.txt
Capturing a single 16-bit mono image
Saved to image_mono16.tiff
Camera settings saved to image_mono16.tiff.txt
Color image not available with this camera
Enabling video mode
Capturing a single 8-bit mono frame
Traceback (most recent call last):
  File "/Users/moriarty/PycharmProjects/ZwoAsi/zwoasi_demo.py", line 163, in <module>
    camera.capture_video_frame(filename=filename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zwoasi/__init__.py", line 491, in capture_video_frame
    data = self.get_video_data(buffer=buffer, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zwoasi/__init__.py", line 424, in get_video_data
    return _get_video_data(self.id, timeout, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zwoasi/__init__.py", line 194, in _get_video_data
    raise zwo_errors[r]
zwoasi.ZWO_Exception: Timeout

Process finished with exit code 1

**Comment by stevemarple** [comment]
The USB bandwidth was set to the camera's specified default value. The demo program now sets it to the advertised minimum value. Settings were reset to their default before video capture, USB bandwidth is now excepted from being reset.It looks like you are now encountering Python 3 compatibility problems. Although I've targeted for Python 2 and 3 compatibility I've not tested yet for Python 3, I'll do that. In the meantime perhaps you can check with Python 2.7?
Release 0.0.13 should fix the USB bandwidth problems.

**Comment by cmoriarty** [comment]
I'll move to python 2.7 as a last resort, we are pretty close to getting this to work.  I just updated to Release 0.0.13.  It works, although you need small tweak in the latest demo code to be compatible with Python 3:

camera.set_control_value(asi.ASI_BANDWIDTHOVERLOAD, camera.get_controls()[b'BandWidth']['MinValue'])

notice the b'. Python 2 will ignore it, and Python 3 needs it.

**Comment by cmoriarty** [comment]
What I mean, is that it fixed the USB bandwidth issue, and the 16-bit image works.  The video mode is still failing with a timeout.

**Comment by cmoriarty** [comment]
I was able to write a simple script that only does video capture, and it works.

import sys
import time
import zwoasi as asi

num_cameras = asi.get_num_cameras()
if num_cameras == 0:
    print('No cameras found')
    sys.exit(0)

cameras_found = asi.list_cameras()  # Models names of the connected cameras

if num_cameras == 1:
    camera_id = 0
    print('Found one camera: %s' % cameras_found[0])
else:
    print('Found %d cameras' % num_cameras)
    for n in range(num_cameras):
        print('    %d: %s' % (n, cameras[n]))
    # TO DO: allow user to select a camera
    camera_id = 0
    print('Using #%d: %s' % (camera_id, cameras_found[camera_id]))

camera = asi.Camera(camera_id)
camera_info = camera.get_camera_property()

camera.set_control_value(asi.ASI_GAIN, 139)
camera.set_control_value(asi.ASI_EXPOSURE, 30000)
camera.set_control_value(asi.ASI_BANDWIDTHOVERLOAD, camera.get_controls()[b'BandWidth']['MinValue'])

print('Enabling video mode')
camera.start_video_capture()
print('Capturing a single 8-bit mono frame')
camera.set_control_value(asi.ASI_BANDWIDTHOVERLOAD, camera.get_controls()[b'BandWidth']['MinValue'])
filename = 'image_video_mono.jpg'
camera.set_image_type(asi.ASI_IMG_RAW8)
camera.capture_video_frame(filename=filename)
print('Saved to %s' % filename)

**Comment by stevemarple** [comment]
The camera controls are supposed to be accessed as strings, I should have fixed that now for Python 3. Timeout is now explicitly cast to an integer. These changes are in 0.0.14. If you are getting a timeout for video mode capture then it seems you may be resetting the USB bandwidth to the default, along with all of the other parameters. In the latest demo code USB bandwidth is not reset. Please confirm that you are using the latest demo. It works for me under Python 2 and 3 with an ASI174 camera.

**Comment by cmoriarty** [comment]
I updated to latest and it works.
